spring.application.name=apnabank-backend

server.port =8080

#Postgres Configuration
spring.datasource.url = jdbc:postgresql://localhost:5432/apnabank_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


#JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' automatically creates/updates database tables based on Entity classes
spring.jpa.hibernate.ddl-auto=update
# Print formatted SQL queries in console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT Secret Configuration
apnabank.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
apnabank.app.jwtExpirationMs=86400000